import { AIModel } from "./columns";

export function getData(): AIModel[] {
  return [
    {
      id: "t-1",
      name: "GPT-2",
      type: "transformer",
      spots: "3/30",
      projectedEarnings: 0.8,
    },
    {
      id: "nn-3",
      name: "VGG-Compact",
      type: "neuralnetwork",
      spots: "8/8",
      projectedEarnings: 1.2,
    },
    {
      id: "t-3",
      name: "RoBERTa-Tiny",
      type: "transformer",
      spots: "15/30",
      projectedEarnings: 0.3,
    },
    {
      id: "nn-4",
      name: "DenseNet-S",
      type: "neuralnetwork",
      spots: "12/12",
      projectedEarnings: 4.1,
    },
    {
      id: "t-4",
      name: "XLM-Mini",
      type: "transformer",
      spots: "9/25",
      projectedEarnings: 2.5,
    },
    {
      id: "nn-5",
      name: "EfficientNet-Lite",
      type: "neuralnetwork",
      spots: "6/6",
      projectedEarnings: 4.8,
    },
    {
      id: "t-5",
      name: "ALBERT-Compact",
      type: "transformer",
      spots: "7/14",
      projectedEarnings: 1.7,
    },
    {
      id: "nn-6",
      name: "MobileNet-S",
      type: "neuralnetwork",
      spots: "3/5",
      projectedEarnings: 0.5,
    },
    {
      id: "t-6",
      name: "DistilBERT-S",
      type: "transformer",
      spots: "11/22",
      projectedEarnings: 1.4,
    },
    {
      id: "nn-7",
      name: "Inception-Mini",
      type: "neuralnetwork",
      spots: "5/7",
      projectedEarnings: 2.8,
    },
    {
      id: "t-7",
      name: "ELECTRA-Tiny",
      type: "transformer",
      spots: "6/18",
      projectedEarnings: 0.9,
    },
    {
      id: "nn-8",
      name: "SqueezeNet-S",
      type: "neuralnetwork",
      spots: "2/3",
      projectedEarnings: 0.2,
    },
    {
      id: "t-8",
      name: "Longformer-Mini",
      type: "transformer",
      spots: "13/26",
      projectedEarnings: 2.8,
    },
    {
      id: "nn-9",
      name: "ShuffleNet-S",
      type: "neuralnetwork",
      spots: "4/8",
      projectedEarnings: 1.6,
    },
    {
      id: "t-9",
      name: "DeBERTa-Lite",
      type: "transformer",
      spots: "10/20",
      projectedEarnings: 4.9,
    },
    {
      id: "nn-10",
      name: "Xception-Mini",
      type: "neuralnetwork",
      spots: "7/10",
      projectedEarnings: 0.1,
    },
  ];
}
