import { AIModel } from "./columns";

export function getData(): AIModel[] {
  return [
    {
      id: "gpt-1",
      name: "GPT-Mini",
      type: "transformer",
      spots: "50/50",
      projectedEarnings: 3.5,
    },
    {
      id: "nn-1",
      name: "ImageNet-S",
      type: "neuralnetwork",
      spots: "2/4",
      projectedEarnings: 7.2,
    },
    {
      id: "t-1",
      name: "BERT-Lite",
      type: "transformer",
      spots: "12/20",
      projectedEarnings: 4.8,
    },
    {
      id: "nn-2",
      name: "ResNet-Mini",
      type: "neuralnetwork",
      spots: "10/10",
      projectedEarnings: 5.9,
    },
    {
      id: "t-2",
      name: "T5-Small",
      type: "transformer",
      spots: "8/15",
      projectedEarnings: 6.3,
    },
    {
      id: "nn-3",
      name: "VGG-Compact",
      type: "neuralnetwork",
      spots: "8/8",
      projectedEarnings: 4.2,
    },
    {
      id: "t-3",
      name: "RoBERTa-Tiny",
      type: "transformer",
      spots: "15/30",
      projectedEarnings: 3.8,
    },
    {
      id: "nn-4",
      name: "DenseNet-S",
      type: "neuralnetwork",
      spots: "12/12",
      projectedEarnings: 5.1,
    },
    {
      id: "t-4",
      name: "XLM-Mini",
      type: "transformer",
      spots: "9/25",
      projectedEarnings: 7.5,
    },
    {
      id: "nn-5",
      name: "EfficientNet-Lite",
      type: "neuralnetwork",
      spots: "6/6",
      projectedEarnings: 8.2,
    },
    {
      id: "t-5",
      name: "ALBERT-Compact",
      type: "transformer",
      spots: "7/14",
      projectedEarnings: 6.7,
    },
    {
      id: "nn-6",
      name: "MobileNet-S",
      type: "neuralnetwork",
      spots: "3/5",
      projectedEarnings: 4.5,
    },
    {
      id: "t-6",
      name: "DistilBERT-S",
      type: "transformer",
      spots: "11/22",
      projectedEarnings: 5.4,
    },
    {
      id: "nn-7",
      name: "Inception-Mini",
      type: "neuralnetwork",
      spots: "5/7",
      projectedEarnings: 6.8,
    },
    {
      id: "t-7",
      name: "ELECTRA-Tiny",
      type: "transformer",
      spots: "6/18",
      projectedEarnings: 4.9,
    },
    {
      id: "nn-8",
      name: "SqueezeNet-S",
      type: "neuralnetwork",
      spots: "2/3",
      projectedEarnings: 3.2,
    },
    {
      id: "t-8",
      name: "Longformer-Mini",
      type: "transformer",
      spots: "13/26",
      projectedEarnings: 7.8,
    },
    {
      id: "nn-9",
      name: "ShuffleNet-S",
      type: "neuralnetwork",
      spots: "4/8",
      projectedEarnings: 5.6,
    },
    {
      id: "t-9",
      name: "DeBERTa-Lite",
      type: "transformer",
      spots: "10/20",
      projectedEarnings: 8.9,
    },
    {
      id: "nn-10",
      name: "Xception-Mini",
      type: "neuralnetwork",
      spots: "7/10",
      projectedEarnings: 6.1,
    },
  ];
}
